export const METADATA_LOADING = 'METADATA_LOADING';
export const CHART_LOADING = 'CHART_LOADING';
export const METADATA_LOADED = 'METADATA_LOADED';
export const METADATA_ERROR = 'METADATA_ERROR';
export const UNMOUNT_PLAYGROUND = 'UNMOUNT_PLAYGROUND';
export const TIME_INTERVAL_CHANGE = 'TIME_INTERVAL_CHANGE';
export const DETAILS_LOADING = 'DETAILS_LOADING';
export const DETAILS_LOADED = 'DETAILS_LOADED';
export const DETAILS_ERROR = 'DETAILS_ERROR';
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
};
